version: '3'

volumes:
  mariadb_data:
      driver: local

services:
  mariadb:
      image: mariadb
      volumes:
        - mariadb_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
        #TZ: Asia/Kolkata
      #ports:
      #  - 3306:3306
  keycloak:
      #image: quay.io/keycloak/keycloak:latest
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        #TZ: Asia/Kolkata
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mariadb
